name = "pibes"
author = "tomas"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bde15b2f1ca7f46286b91ee2bb227321b47449d6e0e7de82d45ed470b0b21dbc"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
