name = "pibes"
author = "pibes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "099acdbf5130c33e6c3aa9314c1e606be7f73f956e475ddb6ca0c4cd70e5e9f4"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
