name = "pibes"
author = "pibes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9efb22fb2b86d6782a022e5912aaf74b417adc76acd8e4bc39a7280525c582c1"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
